package com.forseti.states

/**
 * Catalog of official rules-of-civil-procedure sources for each U.S. state, the
 * District of Columbia, and the federal courts.
 *
 * ## Sourcing strategy (Play-Store safe + low link rot)
 *
 * We adhere to the policy described to the user team:
 *  1. **Only official `.gov` domains.** Every state publishes its civil
 *     procedure rules on its own judiciary or legislature site — there is no
 *     authoritative national aggregator. Where multiple PDFs exist (some
 *     states publish each rule as a separate file), we link to the **index
 *     page** of the official judiciary site so users always land on a live
 *     URL even when individual PDFs are renamed or moved.
 *  2. **Cache on demand.** When a user downloads a rule set, the file is
 *     saved into app-private storage by [StateCacheManager] (long-press a
 *     row to download, long-press again to remove). This avoids broken links
 *     and gives full offline access.
 *  3. **Check for updates.** The Settings tab exposes a "Refresh cached
 *     rules" action that re-downloads everything in the cache from the
 *     authoritative source.
 *
 * ## Why every entry has [lastVerified]
 *
 * Rules pages move occasionally. Carrying a verification stamp lets the UI
 * show users when an entry was last hand-checked, and gives engineers a
 * checklist when sweeping for rot.
 */
data class StateRule(
    val name: String,
    val abbreviation: String,
    val rulesTitle: String,
    val url: String,
    val notes: String? = null,
    val lastVerified: String = "2026-05",
    val isIndexPage: Boolean = false,
    /**
     * Optional fallback URL — usually the state's judiciary homepage. If the
     * primary [url] ever 404s, the UI can offer this as a secondary "open the
     * state courts site" button so the user never hits a dead end.
     */
    val fallbackUrl: String? = null
)

object StateRulesCatalog {
    private const val V = "2026-05"

    /**
     * 50 states + DC. Where direct PDFs exist on a stable judiciary domain we
     * link them; otherwise we link to the official rules **index page** that
     * lists each rule (more durable than a dated PDF URL).
     */
    val states: List<StateRule> = listOf(
        StateRule("Alabama", "AL", "Alabama Rules of Civil Procedure",
            "https://judicial.alabama.gov/library/CivilProcedure",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://judicial.alabama.gov/"),
        StateRule("Alaska", "AK", "Alaska Rules of Civil Procedure",
            "https://courts.alaska.gov/courtrules/civ.htm",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://courts.alaska.gov/"),
        StateRule("Arizona", "AZ", "Arizona Rules of Civil Procedure",
            "https://www.azcourts.gov/rules/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.azcourts.gov/"),
        StateRule("Arkansas", "AR", "Arkansas Rules of Civil Procedure",
            "https://opinions.arcourts.gov/ark/cr/en/nav_date.do",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.arcourts.gov/"),
        StateRule("California", "CA", "California Code of Civil Procedure",
            "https://leginfo.legislature.ca.gov/faces/codesTOCSelected.xhtml?tocCode=CCP",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.ca.gov/"),
        StateRule("Colorado", "CO", "Colorado Rules of Civil Procedure",
            "https://www.coloradojudicial.gov/civil-rules-committee",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.coloradojudicial.gov/"),
        StateRule("Connecticut", "CT", "Connecticut Practice Book",
            "https://www.jud.ct.gov/pb.htm",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.jud.ct.gov/"),
        StateRule("Delaware", "DE", "Delaware Court Rules",
            "https://courts.delaware.gov/rules/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://courts.delaware.gov/"),
        StateRule("District of Columbia", "DC", "DC Superior Court Rules of Civil Procedure",
            "https://www.dccourts.gov/superior-court/rules",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.dccourts.gov/"),
        StateRule("Florida", "FL", "Florida Rules of Civil Procedure",
            "https://www.floridabar.org/rules/rrtfb/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.flcourts.gov/"),
        StateRule("Georgia", "GA", "Georgia Civil Practice / Uniform Rules",
            "https://georgiacourts.gov/uniform-court-rules/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://georgiacourts.gov/"),
        StateRule("Hawaii", "HI", "Hawaii Rules of Civil Procedure",
            "https://www.courts.state.hi.us/legal_references/rules/rulesOfCourt",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.state.hi.us/"),
        StateRule("Idaho", "ID", "Idaho Rules of Civil Procedure",
            "https://isc.idaho.gov/ircp/IRCP",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://isc.idaho.gov/"),
        StateRule("Illinois", "IL", "Illinois Supreme Court Rules",
            "https://www.illinoiscourts.gov/courts/supreme-court/rules-of-the-supreme-court/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.illinoiscourts.gov/"),
        StateRule("Indiana", "IN", "Indiana Rules of Trial Procedure",
            "https://www.in.gov/courts/rules/trial_proc/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.in.gov/courts/"),
        StateRule("Iowa", "IA", "Iowa Rules of Civil Procedure",
            "https://www.legis.iowa.gov/law/courtRules",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.iowacourts.gov/"),
        StateRule("Kansas", "KS", "Kansas Code of Civil Procedure (Chapter 60)",
            "https://www.kscourts.org/Rules-Procedures-Forms/Supreme-Court-Rules",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.kscourts.org/"),
        StateRule("Kentucky", "KY", "Kentucky Rules of Civil Procedure (CR)",
            "https://www.kycourts.gov/Courts/Supreme-Court/Pages/Rules.aspx",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.kycourts.gov/"),
        StateRule("Louisiana", "LA", "Louisiana Code of Civil Procedure",
            "https://www.legis.la.gov/legis/LawSearch.aspx",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.lasc.org/"),
        StateRule("Maine", "ME", "Maine Rules of Civil Procedure",
            "https://www.courts.maine.gov/rules/index.html",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.maine.gov/"),
        StateRule("Maryland", "MD", "Maryland Rules - Title 2 Civil Procedure",
            "https://mdcourts.gov/rules",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://mdcourts.gov/"),
        StateRule("Massachusetts", "MA", "Massachusetts Rules of Civil Procedure",
            "https://www.mass.gov/info-details/massachusetts-law-about-civil-procedure",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.mass.gov/orgs/massachusetts-court-system"),
        StateRule("Michigan", "MI", "Michigan Court Rules",
            "https://courts.michigan.gov/administration/special-initiatives/scao/court-rules/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://courts.michigan.gov/"),
        StateRule("Minnesota", "MN", "Minnesota Rules of Civil Procedure",
            "https://www.revisor.mn.gov/court_rules/cp/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.mncourts.gov/"),
        StateRule("Mississippi", "MS", "Mississippi Rules of Civil Procedure",
            "https://courts.ms.gov/rules/msrulesofcourt.php",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://courts.ms.gov/"),
        StateRule("Missouri", "MO", "Missouri Rules of Civil Procedure",
            "https://www.courts.mo.gov/page.jsp?id=706",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.mo.gov/"),
        StateRule("Montana", "MT", "Montana Rules of Civil Procedure",
            "https://courts.mt.gov/library/topic/court_rules",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://courts.mt.gov/"),
        StateRule("Nebraska", "NE", "Nebraska Court Rules of Pleading in Civil Cases",
            "https://supremecourt.nebraska.gov/supreme-court-rules",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://supremecourt.nebraska.gov/"),
        StateRule("Nevada", "NV", "Nevada Rules of Civil Procedure",
            "https://www.leg.state.nv.us/CourtRules/NRCP.html",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://nvcourts.gov/"),
        StateRule("New Hampshire", "NH", "New Hampshire Superior Court Rules",
            "https://www.courts.nh.gov/rules-statutes",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.nh.gov/"),
        StateRule("New Jersey", "NJ", "NJ Rules Governing Civil Practice (Part IV)",
            "https://www.njcourts.gov/attorneys/rules-of-court",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.njcourts.gov/"),
        StateRule("New Mexico", "NM", "New Mexico Rules of Civil Procedure",
            "https://supremecourt.nmcourts.gov/court-info/court-rules.aspx",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://supremecourt.nmcourts.gov/"),
        StateRule("New York", "NY", "New York CPLR (Civil Practice Law and Rules)",
            "https://www.nysenate.gov/legislation/laws/CVP",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.nycourts.gov/"),
        StateRule("North Carolina", "NC", "NC Rules of Civil Procedure (G.S. 1A-1)",
            "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/ByChapter/Chapter_1A.html",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.nccourts.gov/"),
        StateRule("North Dakota", "ND", "North Dakota Rules of Civil Procedure",
            "https://www.ndcourts.gov/legal-resources/rules/ndrcivp",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.ndcourts.gov/"),
        StateRule("Ohio", "OH", "Ohio Rules of Civil Procedure",
            "https://www.supremecourt.ohio.gov/rules/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.supremecourt.ohio.gov/"),
        StateRule("Oklahoma", "OK", "Oklahoma Pleading Code (Title 12)",
            "https://www.oscn.net/applications/oscn/index.asp?ftdb=STOK&level=1",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.oscn.net/"),
        StateRule("Oregon", "OR", "Oregon Rules of Civil Procedure",
            "https://oregonlegislature.gov/bills_laws/Pages/orcp.aspx",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.oregon.gov/"),
        StateRule("Pennsylvania", "PA", "Pennsylvania Rules of Civil Procedure",
            "https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/231/231toc.html",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.pacourts.us/"),
        StateRule("Rhode Island", "RI", "Rhode Island Superior Court Rules of Civil Procedure",
            "https://www.courts.ri.gov/Courts/SuperiorCourt/Pages/Rules-of-Civil-Procedure.aspx",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.ri.gov/"),
        StateRule("South Carolina", "SC", "South Carolina Rules of Civil Procedure",
            "https://www.sccourts.org/courtreg/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.sccourts.org/"),
        StateRule("South Dakota", "SD", "South Dakota Rules of Civil Procedure (Title 15)",
            "https://sdlegislature.gov/Statutes/Codified_Laws/Title/15",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://ujs.sd.gov/"),
        StateRule("Tennessee", "TN", "Tennessee Rules of Civil Procedure",
            "https://www.tncourts.gov/rules/rules-civil-procedure",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.tncourts.gov/"),
        StateRule("Texas", "TX", "Texas Rules of Civil Procedure",
            "https://www.txcourts.gov/rules-forms/rules-standards/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.txcourts.gov/"),
        StateRule("Utah", "UT", "Utah Rules of Civil Procedure",
            "https://www.utcourts.gov/en/legal-resources/rules/urcp.html",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.utcourts.gov/"),
        StateRule("Vermont", "VT", "Vermont Rules of Civil Procedure",
            "https://www.vermontjudiciary.org/about-vermont-judiciary/court-rules",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.vermontjudiciary.org/"),
        StateRule("Virginia", "VA", "Virginia Rules of the Supreme Court Part 3",
            "https://www.vacourts.gov/courts/scv/amendments/scvrules.html",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.vacourts.gov/"),
        StateRule("Washington", "WA", "Washington Civil Rules (CR)",
            "https://www.courts.wa.gov/court_rules/?fa=court_rules.list&group=sup&set=CR",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.wa.gov/"),
        StateRule("West Virginia", "WV", "West Virginia Rules of Civil Procedure",
            "https://www.courtswv.gov/legal-community/court-rules/civil-procedure",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courtswv.gov/"),
        StateRule("Wisconsin", "WI", "Wisconsin Statutes Chapters 801-806",
            "https://docs.legis.wisconsin.gov/statutes/statutes/801",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.wicourts.gov/"),
        StateRule("Wyoming", "WY", "Wyoming Rules of Civil Procedure",
            "https://www.courts.state.wy.us/court-rules/",
            isIndexPage = true, lastVerified = V,
            fallbackUrl = "https://www.courts.state.wy.us/")
    )

    /**
     * Federal court rules. The uscourts.gov "current rules" landing page is
     * the long-term-stable entry for every federal rules of practice; the
     * dated PDFs underneath rotate yearly so we link the index instead and
     * let the user pick the latest published edition.
     */
    val circuits: List<StateRule> = listOf(
        StateRule("U.S. Supreme Court", "SCOTUS", "Rules of the Supreme Court of the United States",
            "https://www.supremecourt.gov/ctrules/ctrules.aspx",
            isIndexPage = true, lastVerified = V),
        StateRule("Federal Rules of Civil Procedure", "FRCP", "FRCP (current edition)",
            "https://www.uscourts.gov/rules-policies/current-rules-practice-procedure/federal-rules-civil-procedure",
            isIndexPage = true, lastVerified = V),
        StateRule("Federal Rules of Appellate Procedure", "FRAP", "FRAP (current edition)",
            "https://www.uscourts.gov/rules-policies/current-rules-practice-procedure/federal-rules-appellate-procedure",
            isIndexPage = true, lastVerified = V),
        StateRule("Federal Rules of Evidence", "FRE", "FRE (current edition)",
            "https://www.uscourts.gov/rules-policies/current-rules-practice-procedure/federal-rules-evidence",
            isIndexPage = true, lastVerified = V),
        StateRule("Federal Rules of Bankruptcy Procedure", "FRBP", "FRBP (current edition)",
            "https://www.uscourts.gov/rules-policies/current-rules-practice-procedure/federal-rules-bankruptcy-procedure",
            isIndexPage = true, lastVerified = V),
        StateRule("Federal Rules of Criminal Procedure", "FRCRP", "FRCRP (current edition)",
            "https://www.uscourts.gov/rules-policies/current-rules-practice-procedure/federal-rules-criminal-procedure",
            isIndexPage = true, lastVerified = V),
        StateRule("1st Circuit", "CA1", "First Circuit Local Rules",
            "https://www.ca1.uscourts.gov/rules-procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("2nd Circuit", "CA2", "Second Circuit Local Rules",
            "https://www.ca2.uscourts.gov/clerk/case_filing/rules/title28/title_28.html",
            isIndexPage = true, lastVerified = V),
        StateRule("3rd Circuit", "CA3", "Third Circuit Local Rules",
            "https://www.ca3.uscourts.gov/local-appellate-rules",
            isIndexPage = true, lastVerified = V),
        StateRule("4th Circuit", "CA4", "Fourth Circuit Local Rules",
            "https://www.ca4.uscourts.gov/rules-and-procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("5th Circuit", "CA5", "Fifth Circuit Local Rules",
            "https://www.ca5.uscourts.gov/rules-procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("6th Circuit", "CA6", "Sixth Circuit Local Rules",
            "https://www.ca6.uscourts.gov/rules-procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("7th Circuit", "CA7", "Seventh Circuit Local Rules",
            "https://www.ca7.uscourts.gov/rules-procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("8th Circuit", "CA8", "Eighth Circuit Local Rules",
            "https://www.ca8.uscourts.gov/all-rules-and-procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("9th Circuit", "CA9", "Ninth Circuit Local Rules",
            "https://www.ca9.uscourts.gov/rules/",
            isIndexPage = true, lastVerified = V),
        StateRule("10th Circuit", "CA10", "Tenth Circuit Local Rules",
            "https://www.ca10.uscourts.gov/rules-procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("11th Circuit", "CA11", "Eleventh Circuit Local Rules",
            "https://www.ca11.uscourts.gov/rules-procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("D.C. Circuit", "CADC", "D.C. Circuit Local Rules",
            "https://www.cadc.uscourts.gov/internet/home.nsf/content/Rules+and+Operating+Procedures",
            isIndexPage = true, lastVerified = V),
        StateRule("Federal Circuit", "CAFC", "Federal Circuit Local Rules",
            "https://cafc.uscourts.gov/home/rules-procedures-forms/rules-of-practice/",
            isIndexPage = true, lastVerified = V)
    )
}
