package com.forseti.drafts

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.FileOutputStream
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Builds printable PDFs for FRCP-required filings that have no official Pro Se form.
 *
 * Each template uses the shared layout primitives in [DraftDsl]: a standard caption
 * block, numbered paragraph stubs with wide handwriting lines, signature block,
 * and a footer citing the rule the form satisfies.
 *
 * Output is always letter-size (612 x 792 pt) so it prints cleanly to US Letter.
 */
@Singleton
class DraftGenerator @Inject constructor(
    @ApplicationContext private val context: Context
) {
    fun generate(doc: DraftDoc, prefill: DraftPrefill = DraftPrefill()): File {
        require(doc.source is DraftSource.Generated) {
            "DraftGenerator only handles Generated docs; ${doc.id} is ${doc.source}"
        }
        val template = Templates[doc.source.templateId]
            ?: error("No template registered for ${doc.source.templateId}")
        val pdf = PdfDocument()
        val out = File(context.cacheDir, "draft_${doc.id}.pdf")
        try {
            DraftDsl(pdf, doc, prefill).run(template)
            FileOutputStream(out).use { stream -> pdf.writeTo(stream) }
        } finally {
            runCatching { pdf.close() }
        }
        return out
    }
}

/**
 * Optional pre-filled values. Anything left null becomes a blank handwriting line.
 * OCR (M5) populates these before the user prints.
 */
data class DraftPrefill(
    val court: String? = null,
    val plaintiff: String? = null,
    val defendant: String? = null,
    val caseNumber: String? = null,
    val signerName: String? = null,
    val signerAddress: String? = null,
    val signerPhone: String? = null,
    val signerEmail: String? = null,
    val factParagraphs: List<String> = emptyList()
)

private object Templates {
    val all: Map<String, DraftDsl.() -> Unit> = mapOf(
        "answer_general" to {
            caption()
            sectionTitle("ANSWER TO COMPLAINT")
            preamble("Defendant ${blankFor(prefill.defendant, "DEFENDANT'S NAME")}, appearing pro se, answers the Complaint as follows:")
            numberedBlanks(count = 12, label = "Admit / Deny / Lack knowledge")
            sectionTitle("AFFIRMATIVE DEFENSES")
            numberedBlanks(count = 6, label = "State each affirmative defense (Rule 8(c))")
            prayer("WHEREFORE, Defendant requests that the Court dismiss the Complaint with prejudice and grant such further relief as is just.")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti to satisfy FRCP 8(b) and 12(a). Verify local rules before filing.")
        },
        "motion_to_dismiss_12b6" to {
            caption()
            sectionTitle("MOTION TO DISMISS UNDER RULE 12(b)(6)")
            preamble("${blankFor(prefill.defendant, "MOVANT")} moves to dismiss the Complaint under Federal Rule of Civil Procedure 12(b)(6) for failure to state a claim upon which relief can be granted, and in support states:")
            numberedBlanks(count = 8, label = "Numbered grounds for dismissal")
            sectionTitle("MEMORANDUM IN SUPPORT")
            handwritingLines(count = 18)
            prayer("WHEREFORE, the Movant respectfully requests that this Court dismiss the Complaint with prejudice.")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 12(b)(6). Check local rules for accompanying memorandum requirements.")
        },
        "motion_more_definite" to {
            caption()
            sectionTitle("MOTION FOR A MORE DEFINITE STATEMENT")
            preamble("Movant moves under Rule 12(e) for a more definite statement, and states:")
            numberedBlanks(count = 8, label = "Identify each vague allegation and explain why a response is impractical")
            prayer("WHEREFORE, Movant requests an order requiring a more definite statement within 14 days.")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 12(e).")
        },
        "rule_71_disclosure" to {
            caption()
            sectionTitle("DISCLOSURE STATEMENT (RULE 7.1)")
            preamble("Pursuant to Federal Rule of Civil Procedure 7.1, the undersigned states the following:")
            labeledBlank("Nongovernmental corporate party identifies its parent corporation and any publicly held corporation owning 10% or more of its stock as:")
            handwritingLines(count = 4)
            labeledBlank("If a party in a diversity action, the citizenship of every individual or entity whose citizenship is attributed to that party is:")
            handwritingLines(count = 6)
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 7.1.")
        },
        "rule_26f_report" to {
            caption()
            sectionTitle("RULE 26(f) DISCOVERY PLAN AND REPORT OF PARTIES' PLANNING MEETING")
            preamble("Pursuant to Rule 26(f), the parties met on _______________, 20___ and submit the following report:")
            labeledBlank("1. Date of meeting and participants:")
            handwritingLines(count = 3)
            labeledBlank("2. Brief description of the case:")
            handwritingLines(count = 4)
            labeledBlank("3. Proposed discovery plan (subjects, phasing, ESI, privilege issues, limits):")
            handwritingLines(count = 12)
            labeledBlank("4. Proposed deadlines (initial disclosures, fact discovery, expert disclosures, dispositive motions):")
            handwritingLines(count = 6)
            labeledBlank("5. Trial readiness estimate:")
            handwritingLines(count = 2)
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 26(f).")
        },
        "interrogatories_33" to {
            caption()
            sectionTitle("PLAINTIFF/DEFENDANT'S FIRST SET OF INTERROGATORIES")
            preamble("Pursuant to Rule 33, ${blankFor(prefill.plaintiff, "PROPOUNDING PARTY")} requests that ${blankFor(prefill.defendant, "RESPONDING PARTY")} answer the following interrogatories under oath within 30 days. (Limit: 25 including subparts.)")
            labeledBlank("Definitions and instructions:")
            handwritingLines(count = 4)
            numberedBlanks(count = 25, label = "Interrogatory")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 33. Numerical limit (25) includes subparts.")
        },
        "rfp_34" to {
            caption()
            sectionTitle("REQUESTS FOR PRODUCTION OF DOCUMENTS")
            preamble("Pursuant to Rule 34, the responding party shall produce the following documents within 30 days at a mutually agreeable place and time:")
            labeledBlank("Definitions and instructions:")
            handwritingLines(count = 4)
            numberedBlanks(count = 20, label = "Request for production")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 34.")
        },
        "rfa_36" to {
            caption()
            sectionTitle("REQUESTS FOR ADMISSION")
            preamble("Pursuant to Rule 36, the responding party must admit or deny each request below within 30 days. Failure to respond results in the matter being deemed ADMITTED.")
            numberedBlanks(count = 25, label = "Request for admission")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 36. 30-day deadline is automatic.")
        },
        "msj_56" to {
            caption()
            sectionTitle("MOTION FOR SUMMARY JUDGMENT")
            preamble("Movant moves under Rule 56 for summary judgment on all (or specified) claims, on the ground that no genuine dispute of material fact exists and Movant is entitled to judgment as a matter of law.")
            sectionTitle("STATEMENT OF UNDISPUTED MATERIAL FACTS")
            numberedBlanks(count = 20, label = "Numbered fact with citation to record")
            sectionTitle("MEMORANDUM OF LAW")
            handwritingLines(count = 24)
            prayer("WHEREFORE, Movant respectfully requests that this Court grant summary judgment in its favor.")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 56. Many districts require a separate Statement of Material Facts; check local rules.")
        },
        "subpoena_45" to {
            caption()
            sectionTitle("SUBPOENA")
            preamble("To: __________________________________________")
            labeledBlank("YOU ARE COMMANDED TO (testify / produce documents / permit inspection):")
            handwritingLines(count = 4)
            labeledBlank("Place / Date / Time:")
            handwritingLines(count = 3)
            labeledBlank("Documents or items requested:")
            handwritingLines(count = 8)
            signatureBlock()
            footer("Informal Forseti subpoena form. The federal AO 88/88B forms are preferred where available.")
        },
        "cert_of_service" to {
            caption()
            sectionTitle("CERTIFICATE OF SERVICE")
            preamble("I certify that on _______________, 20___, I served the foregoing on the following parties by the means indicated:")
            handwritingLines(count = 8)
            signatureBlock()
            footer("Form generated by Forseti for FRCP 5(b).")
        },
        "motion_default_55" to {
            caption()
            sectionTitle("MOTION FOR ENTRY OF DEFAULT AND DEFAULT JUDGMENT")
            preamble("Plaintiff moves under Rule 55 for entry of default by the Clerk and, thereafter, for default judgment because:")
            numberedBlanks(count = 6, label = "Statement of facts supporting default")
            prayer("WHEREFORE, Plaintiff requests that the Clerk enter default and that this Court enter default judgment in the amount of \$______________.")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 55. Some courts require a sworn affidavit; attach one if needed.")
        },
        "motion_new_trial_59" to {
            caption()
            sectionTitle("MOTION FOR NEW TRIAL / TO ALTER OR AMEND JUDGMENT")
            preamble("Movant moves under Rule 59(a) and/or 59(e) for a new trial and/or to alter or amend the judgment entered on _______________, 20___, on the following grounds:")
            numberedBlanks(count = 8, label = "Numbered ground")
            prayer("WHEREFORE, Movant requests that this Court grant a new trial and/or alter the judgment as set forth above.")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 59. WARNING: must be filed within 28 days of judgment entry.")
        },
        "motion_relief_60" to {
            caption()
            sectionTitle("MOTION FOR RELIEF FROM JUDGMENT (RULE 60(b))")
            preamble("Movant moves under Rule 60(b) for relief from the judgment entered on _______________, 20___, on the following ground(s):")
            labeledBlank("Check all that apply: __ mistake/inadvertence; __ newly discovered evidence; __ fraud; __ void judgment; __ judgment satisfied/discharged; __ any other reason that justifies relief.")
            handwritingLines(count = 18)
            prayer("WHEREFORE, Movant requests relief from the judgment.")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 60(b). 1 year deadline applies to grounds (1)-(3).")
        },
        "amended_complaint_15" to {
            caption()
            sectionTitle("AMENDED COMPLAINT")
            preamble("Pursuant to Rule 15, ${blankFor(prefill.plaintiff, "PLAINTIFF")} files this Amended Complaint as a matter of course / with leave of court / by consent of opposing party (circle one):")
            sectionTitle("PARTIES")
            handwritingLines(count = 6)
            sectionTitle("JURISDICTION & VENUE")
            handwritingLines(count = 6)
            sectionTitle("FACTUAL ALLEGATIONS")
            numberedBlanks(count = 20, label = "Numbered fact")
            sectionTitle("CAUSES OF ACTION")
            numberedBlanks(count = 6, label = "Count")
            prayer("WHEREFORE, Plaintiff prays for judgment as set forth above plus costs and such further relief as the Court deems just.")
            signatureBlock()
            certificateOfService()
            footer("Form generated by Forseti for FRCP 15.")
        }
    )

    operator fun get(id: String): (DraftDsl.() -> Unit)? = all[id]
}

/**
 * Tiny DSL over PdfDocument that lays out caption blocks, paragraph stubs,
 * handwriting lines, signature blocks, and a footer.
 *
 * Keeps a running cursor (left, top) and starts a new page when content would
 * overflow the bottom margin.
 */
class DraftDsl(
    private val pdf: PdfDocument,
    val doc: DraftDoc,
    val prefill: DraftPrefill
) {
    private var pageNumber = 0
    private var page: PdfDocument.Page? = null
    private var canvas: Canvas? = null
    private var cursorY: Float = 0f

    private val pageWidth = 612
    private val pageHeight = 792
    private val marginX = 54f
    private val marginTop = 54f
    private val marginBottom = 54f

    private val titlePaint = TextPaint().apply {
        isAntiAlias = true
        color = Color.BLACK
        textSize = 14f
        typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
    }
    private val bodyPaint = TextPaint().apply {
        isAntiAlias = true
        color = Color.BLACK
        textSize = 11f
        typeface = Typeface.SERIF
    }
    private val labelPaint = TextPaint().apply {
        isAntiAlias = true
        color = Color.DKGRAY
        textSize = 9.5f
        typeface = Typeface.create(Typeface.SERIF, Typeface.ITALIC)
    }
    private val linePaint = Paint().apply {
        color = Color.LTGRAY
        strokeWidth = 0.6f
        style = Paint.Style.STROKE
        isAntiAlias = true
    }

    fun run(template: DraftDsl.() -> Unit) {
        // If template() throws, we must still finishPage() — otherwise
        // PdfDocument.writeTo() throws IllegalStateException ("Current page not closed")
        // and the app crashes while "Building PDF…" is showing.
        try {
            startPage()
            template()
        } finally {
            finishPage()
        }
    }

    private fun startPage() {
        pageNumber++
        val info = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
        page = pdf.startPage(info)
        canvas = page!!.canvas
        cursorY = marginTop
        if (pageNumber > 1) drawHeader("(continued)")
    }

    private fun finishPage() {
        page?.let { pdf.finishPage(it) }
        page = null
        canvas = null
    }

    private fun newPage() {
        finishPage()
        startPage()
    }

    private fun ensureSpace(needed: Float) {
        if (cursorY + needed > pageHeight - marginBottom) newPage()
    }

    private fun drawHeader(label: String) {
        val c = canvas ?: return
        c.drawText(label, marginX, marginTop - 12f, labelPaint)
    }

    fun caption() {
        val width = pageWidth - 2 * marginX
        canvas?.drawText("UNITED STATES DISTRICT COURT", marginX, cursorY + 12f, titlePaint)
        cursorY += 16f
        labeledLine("DISTRICT OF", prefill.court)
        cursorY += 4f
        canvas?.drawLine(marginX, cursorY, marginX + width, cursorY, linePaint)
        cursorY += 14f
        labeledLine("Plaintiff(s)", prefill.plaintiff)
        canvas?.drawText("v.", marginX, cursorY + 12f, bodyPaint)
        cursorY += 16f
        labeledLine("Defendant(s)", prefill.defendant)
        cursorY += 4f
        canvas?.drawLine(marginX, cursorY, marginX + width, cursorY, linePaint)
        cursorY += 14f
        labeledLine("Case No.", prefill.caseNumber)
        cursorY += 8f
        canvas?.drawText("Re: ${doc.title}  (${doc.ruleCitation})", marginX, cursorY + 10f, labelPaint)
        cursorY += 16f
        canvas?.drawLine(marginX, cursorY, marginX + width, cursorY, linePaint)
        cursorY += 12f
    }

    private fun labeledLine(label: String, value: String?) {
        ensureSpace(20f)
        val c = canvas ?: return
        c.drawText("$label: ", marginX, cursorY + 12f, bodyPaint)
        val labelWidth = bodyPaint.measureText("$label: ")
        val xLine = marginX + labelWidth
        val xEnd = pageWidth - marginX
        c.drawLine(xLine, cursorY + 14f, xEnd, cursorY + 14f, linePaint)
        if (!value.isNullOrBlank()) {
            c.drawText(value, xLine + 2f, cursorY + 12f, bodyPaint)
        }
        cursorY += 22f
    }

    fun sectionTitle(title: String) {
        ensureSpace(28f)
        cursorY += 8f
        canvas?.drawText(title, marginX, cursorY + 12f, titlePaint)
        cursorY += 18f
    }

    fun preamble(text: String) {
        paragraph(text)
        cursorY += 4f
    }

    fun paragraph(text: String) {
        if (text.isBlank()) return
        if (canvas == null) return
        val width = (pageWidth - 2 * marginX).toInt()
        val layout = StaticLayout.Builder.obtain(text, 0, text.length, bodyPaint, width)
            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
            .setLineSpacing(2f, 1.0f)
            .build()
        ensureSpace(layout.height.toFloat() + 6f)
        val c = canvas ?: return
        c.save()
        c.translate(marginX, cursorY)
        layout.draw(c)
        c.restore()
        cursorY += layout.height + 6f
    }

    fun labeledBlank(label: String) {
        paragraph(label)
        handwritingLines(count = 1)
    }

    fun handwritingLines(count: Int) {
        val xStart = marginX
        val xEnd = pageWidth - marginX
        repeat(count) {
            ensureSpace(22f)
            cursorY += 16f
            canvas?.drawLine(xStart, cursorY, xEnd, cursorY, linePaint)
            cursorY += 4f
        }
        cursorY += 6f
    }

    fun numberedBlanks(count: Int, label: String) {
        val xEnd = pageWidth - marginX
        for (i in 1..count) {
            ensureSpace(40f)
            val prefix = "$i. "
            canvas?.drawText("$prefix$label:", marginX, cursorY + 12f, labelPaint)
            cursorY += 18f
            canvas?.drawLine(marginX, cursorY, xEnd, cursorY, linePaint)
            cursorY += 18f
            canvas?.drawLine(marginX, cursorY, xEnd, cursorY, linePaint)
            cursorY += 8f
        }
    }

    fun prayer(text: String) {
        cursorY += 6f
        paragraph(text)
    }

    fun signatureBlock() {
        ensureSpace(120f)
        cursorY += 14f
        canvas?.drawText("Respectfully submitted,", marginX, cursorY + 12f, bodyPaint)
        cursorY += 36f
        canvas?.drawLine(marginX, cursorY, marginX + 240f, cursorY, linePaint)
        canvas?.drawText("Signature", marginX, cursorY + 11f, labelPaint)
        cursorY += 20f
        labeledLine("Printed name", prefill.signerName)
        labeledLine("Address", prefill.signerAddress)
        labeledLine("Phone", prefill.signerPhone)
        labeledLine("Email", prefill.signerEmail)
        labeledLine("Date", null)
    }

    fun certificateOfService() {
        sectionTitle("CERTIFICATE OF SERVICE")
        paragraph("I certify that on the date below I served a true copy of the foregoing on all parties of record by the means indicated.")
        handwritingLines(count = 3)
        labeledLine("Date", null)
    }

    fun footer(text: String) {
        if (text.isBlank()) return
        val width = (pageWidth - 2 * marginX).toInt()
        val layout = StaticLayout.Builder.obtain(text, 0, text.length, labelPaint, width)
            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
            .build()
        ensureSpace(layout.height.toFloat() + 8f)
        val c = canvas ?: return
        c.save()
        c.translate(marginX, (pageHeight - marginBottom + 8f))
        layout.draw(c)
        c.restore()
    }

    fun blankFor(value: String?, placeholder: String): String =
        value?.takeIf { it.isNotBlank() } ?: "[$placeholder]"
}
